### ISSUE TITLE
Error in default.prior

### ISSUE THREAD

**Issue by kstandvoss** [boryspaulewicz/bhsdtr2#1]
Hi, great package. I am trying to fit a meta-dprime model to my data. Unfortunately I get an error message saying:

`Error in default.prior(par, ncol(sdata[[v]]), prior.par, model, links,  :
     object 'delta.size' not found
`

if I try a minimal example from the repository Readme like this:

`
library(bhsdtr2)

gabor$r.binary = combined.response(gabor$stim, accuracy = gabor$acc)
m = bhsdtr(c(dprim ~ 1, thr ~ 1),
          r.binary ~ stim,
          gabor[gabor$order == 'DECISION-RATING' & gabor$duration == '32 ms' &
          gabor$id == 1,])
`

I get the same error message. Am I doing something wrong or is it some error with the package? 

Hope you can help me. Kind regards

**Comment by boryspaulewicz** [comment]
Thank you for the notification. I did not realize I had a bad commit. 
I have pushed a bugfix - please try with the latest version and tell me if this problem is now solved. 
Also, you may want to consider the new link function for the d' and meta-d' parameters. It is called "id_log". It is easier to specify weakly-informative priors for the d' and meta-d' parameters, but iit can be used only when you have a separate intercepts parametrization. e.g., metad ~ -1 + f1 ...

**Comment by kstandvoss** [comment]
Thanks for the fast reply. Not it works!
I will also give the new link function a try. Thanks for the suggestion.
